---
title: "Assignment 1: Introduction"
author: Jess Garcia
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Salk_A03_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have almost no experience with data analytics, R, and Git. I have worked with Stata in my Public Policy statistics course at Sanford.I have atteneded a workshop or two on R but have forgotten almost everything.

2. Are there any components of the course about which you feel confident?

> Answer: I feel okay about my understanding of statistics basics, but I am not sure how much use that will be on the data analaysis side of things.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am pretty intimidated by the entire course. I am apprehensive about anything data science, coding, programming, etc. but I am excited to learn! I'm just hoping the learning will be taken slowly and step-by-step for us rubes.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: 

https://github.com/jmg144/Environmental_Data_Analytics_2021.git
